/// Country flag helpers.
///
/// Jolpica returns full country names (e.g. "United Kingdom"), but flag
/// emojis require an ISO 3166-1 alpha-2 code (e.g. "GB"). This maps the
/// names used on the F1 calendar to their codes and renders a flag emoji.
library;

/// Maps a country name (as returned by Jolpica) to its ISO 3166-1 alpha-2
/// code. Covers the current F1 calendar plus common past hosts.
const Map<String, String> countryFlagCode = {
  'United Kingdom': 'GB',
  'Great Britain': 'GB',
  'UK': 'GB',
  'United States': 'US',
  'USA': 'US',
  'Italy': 'IT',
  'Australia': 'AU',
  'Japan': 'JP',
  'China': 'CN',
  'Bahrain': 'BH',
  'Saudi Arabia': 'SA',
  'Monaco': 'MC',
  'Canada': 'CA',
  'Spain': 'ES',
  'Austria': 'AT',
  'Netherlands': 'NL',
  'Belgium': 'BE',
  'Hungary': 'HU',
  'Azerbaijan': 'AZ',
  'Singapore': 'SG',
  'Mexico': 'MX',
  'Brazil': 'BR',
  'Qatar': 'QA',
  'United Arab Emirates': 'AE',
  'UAE': 'AE',
  'Argentina': 'AR',
  'Germany': 'DE',
  'France': 'FR',
  'Turkey': 'TR',
  'India': 'IN',
  'Malaysia': 'MY',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  'Russia': 'RU',
  'Thailand': 'TH',
  'Vietnam': 'VN',
  'Indonesia': 'ID',
  'Portugal': 'PT',
  'Ireland': 'IE',
  'Finland': 'FI',
  'Switzerland': 'CH',
  'New Zealand': 'NZ',
  'Luxembourg': 'LU',
  'Morocco': 'MA',
  'Sweden': 'SE',
  'Denmark': 'DK',
  'Norway': 'NO',
  'Poland': 'PL',
  'Czech Republic': 'CZ',
  'Greece': 'GR',
  'Croatia': 'HR',
  'Slovenia': 'SI',
  'Slovakia': 'SK',
  'Ukraine': 'UA',
  'Colombia': 'CO',
  'Peru': 'PE',
  'Chile': 'CL',
  'Uruguay': 'UY',
  'Venezuela': 'VE',
  'Hong Kong': 'HK',
  'Macau': 'MO',
  'Taiwan': 'TW',
  'Philippines': 'PH',
  'Egypt': 'EG',
  'Israel': 'IL',
  'Jordan': 'JO',
  'Lebanon': 'LB',
  'Kuwait': 'KW',
  'Oman': 'OM',
  'Iran': 'IR',
  'Pakistan': 'PK',
  'Bangladesh': 'BD',
  'Sri Lanka': 'LK',
  'Nepal': 'NP',
  'Mongolia': 'MN',
  'Kazakhstan': 'KZ',
  'Uzbekistan': 'UZ',
  'Georgia': 'GE',
  'Armenia': 'AM',
  'Serbia': 'RS',
  'Bulgaria': 'BG',
  'Lithuania': 'LT',
  'Latvia': 'LV',
  'Estonia': 'EE',
  'Iceland': 'IS',
  'Malta': 'MT',
  'Cyprus': 'CY',
  'San Marino': 'SM',
  'Vatican City': 'VA',
  'Andorra': 'AD',
  'Liechtenstein': 'LI',
  'Faroe Islands': 'FO',
  'Greenland': 'GL',
  'Puerto Rico': 'PR',
  'Cuba': 'CU',
  'Jamaica': 'JM',
  'Bahamas': 'BS',
  'Trinidad and Tobago': 'TT',
  'Panama': 'PA',
  'Costa Rica': 'CR',
  'Guatemala': 'GT',
  'Honduras': 'HN',
  'El Salvador': 'SV',
  'Nicaragua': 'NI',
  'Dominican Republic': 'DO',
  'Haiti': 'HT',
  'Bolivia': 'BO',
  'Paraguay': 'PY',
  'Ecuador': 'EC',
  'Guyana': 'GY',
  'Suriname': 'SR',
  'Fiji': 'FJ',
  'Samoa': 'WS',
  'Tonga': 'TO',
  'Papua New Guinea': 'PG',
  'New Caledonia': 'NC',
  'French Polynesia': 'PF',
  'Mauritius': 'MU',
  'Seychelles': 'SC',
  'Kenya': 'KE',
  'Nigeria': 'NG',
  'Ghana': 'GH',
  'Senegal': 'SN',
  'Ivory Coast': 'CI',
  'Cameroon': 'CM',
  'Ethiopia': 'ET',
  'Tanzania': 'TZ',
  'Uganda': 'UG',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
  'Botswana': 'BW',
  'Namibia': 'NA',
  'Angola': 'AO',
  'Mozambique': 'MZ',
  'Madagascar': 'MG',
  'Tunisia': 'TN',
  'Algeria': 'DZ',
  'Libya': 'LY',
  'Sudan': 'SD',
  'Yemen': 'YE',
  'Syria': 'SY',
  'Iraq': 'IQ',
  'Afghanistan': 'AF',
  'Turkmenistan': 'TM',
  'Kyrgyzstan': 'KG',
  'Tajikistan': 'TJ',
  'Bhutan': 'BT',
  'Maldives': 'MV',
  'Brunei': 'BN',
  'Cambodia': 'KH',
  'Laos': 'LA',
  'Myanmar': 'MM',
  'North Korea': 'KP',
  'Macedonia': 'MK',
  'Montenegro': 'ME',
  'Bosnia and Herzegovina': 'BA',
  'Albania': 'AL',
  'Moldova': 'MD',
  'Belarus': 'BY',
  'Kosovo': 'XK',
};

/// Builds a flag emoji from an ISO 3166-1 alpha-2 [code] (e.g. "GB" → 🇬🇧).
///
/// Each letter is converted to its regional indicator symbol
/// (U+1F1E6 for 'A' ... U+1F1FF for 'Z').
String flagEmoji(String code) {
  return code
      .toUpperCase()
      .split('')
      .map((c) => String.fromCharCode(c.codeUnitAt(0) + 0x1F1A5))
      .join();
}

/// Returns the flag emoji for a Jolpica [countryName], or `null` if the
/// country isn't in [countryFlagCode].
String? flagEmojiForCountry(String countryName) {
  final code = countryFlagCode[countryName];
  return code == null ? null : flagEmoji(code);
}
